services:
  db:
    image: postgres:16-alpine
    container_name: universityDB
    ports:
      - "5432:5432"
    env_file:
      - .env.local
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: universityRedis
    ports:
      - '6379:6379'
    env_file:
      - .env.local
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres:
  cache:
    driver: local
